#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

#define MAP_TYPE_NONE        0
#define MAP_TYPE_TOWN        1
#define MAP_TYPE_CITY        2
#define MAP_TYPE_ROUTE       3
#define MAP_TYPE_UNDERGROUND 4
#define MAP_TYPE_UNDERWATER  5
#define MAP_TYPE_OCEAN_ROUTE 6
#define MAP_TYPE_UNKNOWN     7 // Not used by any map.
#define MAP_TYPE_INDOOR      8
#define MAP_TYPE_SECRET_BASE 9

#define MAP_BATTLE_SCENE_NORMAL        0
#define MAP_BATTLE_SCENE_GYM           1 // unused; see MAP_BATTLE_SCENE_GYM_NORMAL onward
#define MAP_BATTLE_SCENE_MAGMA         2
#define MAP_BATTLE_SCENE_AQUA          3
#define MAP_BATTLE_SCENE_SIDNEY        4
#define MAP_BATTLE_SCENE_PHOEBE        5
#define MAP_BATTLE_SCENE_GLACIA        6
#define MAP_BATTLE_SCENE_DRAKE         7
#define MAP_BATTLE_SCENE_FRONTIER      8
#define MAP_BATTLE_SCENE_GYM_NORMAL	   9
#define MAP_BATTLE_SCENE_GYM_FIGHTING 10
#define MAP_BATTLE_SCENE_GYM_FLYING   11
#define MAP_BATTLE_SCENE_GYM_POISON   12
#define MAP_BATTLE_SCENE_GYM_GROUND   13
#define MAP_BATTLE_SCENE_GYM_ROCK     14
#define MAP_BATTLE_SCENE_GYM_BUG      15
#define MAP_BATTLE_SCENE_GYM_GHOST    16
#define MAP_BATTLE_SCENE_GYM_STEEL    17
#define MAP_BATTLE_SCENE_GYM_FIRE     18
#define MAP_BATTLE_SCENE_GYM_WATER    19
#define MAP_BATTLE_SCENE_GYM_GRASS    20
#define MAP_BATTLE_SCENE_GYM_ELECTRIC 21
#define MAP_BATTLE_SCENE_GYM_PSYCHIC  22
#define MAP_BATTLE_SCENE_GYM_ICE      23
#define MAP_BATTLE_SCENE_GYM_DRAGON   24
#define MAP_BATTLE_SCENE_GYM_DARK     25
#define MAP_BATTLE_SCENE_GYM_FAIRY    26

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
